global:
  resolve_timeout: 1m

templates: 
- 'templates/*'

route:
  group_by: ['...']
  group_wait: 0s
  group_interval: 5m
  repeat_interval: 1h
  
  routes:
    - receiver: 'seinetwork-rules
      group_by: ['...']

  receiver: seinetwork-rules

receivers:
- name: 'seinetwork-rules'
  pagerduty_configs:
    - service_key: 'REPLACEME'
